version: 2
updates:
  # Actualizaciones para el ecosistema npm (Monorepo)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "javascript"

  # Actualizaciones para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci/cd"
