name: Multi-Project Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Única instalación para todo el Monorepo
      - name: Install dependencies (Monorepo)
        run: npm install --legacy-peer-deps

      - name: Prepare Out Dir
        run: mkdir -p out

      # BUILD BPMN Modeler
      - name: Build BPMN Modeler
        run: |
          npm run build --workspace=bpmn-modeler
          mkdir -p out/BPMN-Modeler
          cp -r BPMN-Modeler/dist/* out/BPMN-Modeler/

      # BUILD Shipment Tracker
      - name: Build Shipment Tracker
        run: |
          npm run build --workspace=shipment-tracker
          mkdir -p out/Shipment-Tracker
          cp -r Shipment-Tracker/dist/* out/Shipment-Tracker/

      # BUILD Logistics Dashboard
      - name: Build Logistics Dashboard
        run: |
          npm run build --workspace=logistics-dashboard
          mkdir -p out/Logistics-Dashboard
          cp -r Logistics-Dashboard/dist/* out/Logistics-Dashboard/

      # COPY Root Index
      - name: Copy Root Index
        run: cp index.html out/

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
